routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/check_user', 'UserController@checkUser')->name('chckUser');

Route::resource('admin', 'AdminController');
 // Route::get('/edit', ['as' => 'admin.update', 'uses' => 'AboutController@edit']);
Route::resource('listing', 'ListingController');
Route::resource('user', 'UserController');
Route::get('user/create', 'UserController@create');
Route::post('/user', 'UserController@store');

resources/views/admin/NewList.blade.php
@extends('layouts.app')
@section('content')
	<div class="container">

		 <h2 class="card-title text-info">Create New List</h2>
		<br>
		
		<form method="POST" action="{{route('listing.store')}}" enctype="multipart/form-data">
			@csrf
			<div class="form-group">
				<label for="list_name">List Name: </label>
				<input type="text" class="form-control" name="list_name" id="list_name">
			</div>
			<div class="form-group">
				<label for="address">Address: </label>
				<input type="text" class="form-control" name="address" id="address">
			</div>
			<div class="form-group">
				<label for="latitude">Latitude: </label>
				<input type="number" class="form-control" name="latitude" id="latitude">
			</div>
			<div class="form-group">
				<label for="longitude">Longitude: </label>
				<input type="number" class="form-control" name="longitude" id="longitude">
			</div>

			<input type="hidden" class="form-control" name="submitter_id" id="submitter_id" value="{{ Auth::user()->id }}">

			<div class="fa-pull-right">
				<button type="reset" class="btn btn-outline-info">Reset</button>
				<button type="submit" class="btn btn-info">Submit</button>
			</div>
		</form>
	</div>
@endsection

resources/views/admin/create.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
      <h2 class="card-title text-info">Create New User</h2>
    <br>
    <form method="post" action="{{route('admin.store')}}" enctype="multipart/form-data">
    
    @csrf
        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="name">Name:</label>
                <input type="text" class="form-control" name="name" required>
            </div>
        </div>

        
        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="email">Email</label>
                <input type="text" class="form-control" name="email" required>
             </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="password">Password</label>
                <input type="text" class="form-control" name="password" required>
             </div>
        </div>


       
        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="type">Type</label>
                <input type="text" class="form-control" name="type" required>
             </div>
        </div>
       
             
       

         <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4" style="margin-top:60px">
                <button type="submit" class="btn btn-outline-info">Save</button>
                <a href="{{action('AdminController@index')}}" class="btn btn-info">Back</a>
             </div>
        </div>
    </form>
</div>

@endsection

resources/views/admin/edit.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
      <h2 class="card-title text-info">Update Users</h2>
    <br>

    <form method="post" action="{{route('admin.update', $user->id)}}" enctype="multipart/form-data">
   
    @csrf
        
        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="name">Name:</label>
                <input type="text" class="form-control" name="name" value="{{$user->name}}"required>
            </div>
        </div>

       <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="email">Email</label>
                <input type="text" class="form-control" name="email" value="{{$user->email}}"required>
             </div>
        </div>

       
        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="type">Type</label>
                <input type="text" class="form-control" name="type" value="{{$user->type}}"required>
             </div>
        </div>
       
         <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4" style="margin-top:60px">
                <button type="submit" class="btn btn-outline-info">Save</button>
                <a href="{{action('AdminController@index')}}" class="btn btn-info">Back</a>
             </div>
        </div>
        @method('put')
    </form>
</div>


@endsection

resources/views/admin/editList.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
      <h2 class="card-title text-info">Update Listing Table</h2>
    <br>

    <form method="post" action="{{route('listing.update', $listing->id)}}" enctype="multipart/form-data">
   
    @csrf
        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="list_name">List Name:</label>
                <input type="text" class="form-control" name="list_name" value="{{$listing->list_name}}" required>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="address">Address</label>
                <input type="text" class="form-control" name="address" value="{{$listing->address}}" required>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="latitude">Latitude:</label>
                <input type="text" class="form-control" name="latitude" value="{{$listing->latitude}}"  required>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="longitude">Longitude</label>
                <input type="text" class="form-control" name="longitude" value="{{$listing->longitude}}" required>
             </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="submitter_id">Submitter Id</label>
                <input type="text" name="submitter_id"  class="form-control" value="{{$listing->submitter_id}}">
                
            </div>
        </div>


         <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4" style="margin-top:60px">
                <button type="submit" class="btn btn-outline-info">Save</button>
                <a href="{{action('ListingController@index')}}" class="btn btn-info">Back</a>
             </div>
        </div>
        @method('put')
    </form>
</div>

@endsection

resources/views/admin/index.blade.php
@extends('layouts.app')
@section('content')
    <main role="main" class="container">
        <div class="d-flex align-items-center p-3 my-3 rounded border-bottom">
            <h2 class="card-title text-info">List of Users</h2>
        </div>
            <table class="table">
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Type</th>
                    <th colspan="2">Action</th>
                </tr>
                <tbody>
                @foreach($user as $u)
                <tr>
                    <td>{{$u->name}}</td>
                    <td>{{$u->email}}</td>
                    <td>{{$u->type}}</td>
                    <td>
                        <div class="row">
                            <div class="col-md-2">
                                <a href="{{action('AdminController@edit', $u->id)}}" class="btn btn-warning">Edit</a>
                            </div>
                            <div class="col-md-2">
                                <form action="{{action('AdminController@destroy', $u->id)}}" method="post">
                                    @csrf
                                    <input name="_method" type="hidden" value="DELETE">
                                    <button class="btn btn-info" type="submit">Delete</button>
                                </form>
                            </div>
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </main>
@endsection

 

resources/views/admin/listing.blade.php
@extends('layouts.app')
@section('content')

   
    <main role="main" class="container">
        <div class="d-flex align-items-center p-3 my-3 rounded border-bottom">
            <h2 class="card-title text-info">Listing&nbsp;<i class="fas fa-hand-holding-heart"></i></h2>
        </div>
        <div class="my-3 p-3 bg-white rounded box-shadow">
            
            <table class="table" style="color: black;">
                <tr>
                   
                    <th>List Name</th>
                    <th>Address</th>
                    <th>Latitude</th>
                    <th>Longitude</th>
                    <th>Submitter Id</th>
                   
                       <th span="2">Action</th>
                </tr>
                @foreach($listing as $l)
                <tr>
                    <td>{{$l->list_name}}</td>
                    <td>{{$l->address}}</td>
                    <td>{{$l->latitude}}</td>
                    <td>{{$l->longitude}}</td>
                    <td>{{$l->submitter_id}}</td>
                    <td>
                        <a href="{{action('ListingController@edit', $l->id)}}" class="btn btn-warning">Edit</a>
                    </td>
                    <td>
                        <form action="{{action('ListingController@destroy', $l->id)}}" method="post">
                            @csrf
                            <input name="_method" type="hidden" value="DELETE">
                            <button class="btn btn-info" type="submit">Delete</button>
                        </form>
                    </td>
                 </tr>
                @endforeach
            </table>
        </div>
    </main>

@endsection